### PR TITLE
Issue 72 Resolved

### PR DESCRIPTION
**Pull request by NateMietk**
Only the folders created during unzip will be deleted. All custom folders/files and the stackedFiles output folder will be retained.

### CODE REVIEW

**Comment by cklunch** [comment]
@NateMietk 
This isn't the file handling I had envisioned for this. All zip files are now getting deleted, and the folders of unstacked files are retained. So we haven't removed the risk of deleting other files the user has in the download folder (if they have other zip files), and we've gone back to cluttering up their drives.

The goal in my mind is (1) only delete things involved in the file download and stacking, and (2) delete everything involved in the file download and stacking, except for the contents of the stackedFiles folder and the documents, if 'Include documents' was checked on the portal. I think the best way to do this is to create a running list of files as stackByTable does its thing, and delete them all at the end.

Also, please name pull requests with a description of what you've changed. You can tag the issue in the PR message.

**Comment by NateMietk** [comment]
@cklunch I am not seeing this action: "All zip files are now getting deleted, and the folders of unstacked files are retained. So we haven't removed the risk of deleting other files the user has in the download folder (if they have other zip files), and we've gone back to cluttering up their drives."

Regardless, I have another fix in mind. It is as follows:

1. Return the list of zip files created during `unzipZipfileParallel` 
2. Use that as the input to `saveUnzippedFiles` instead of the `orig` object as before.
3. Delete all folders and zip files in `saveUnzippedFiles` that contain the basename of the zip file.

This should do what you are after. Please let me know if you were thinking of something different.

**Comment by NateMietk** [comment]
@cklunch Implemented the new fix. Let me know if this is more of what you were envisioning.

**Comment by cklunch** [comment]
@NateMietk 
Testing on a portal file ended with this error:
`Error in paste(zipList, collapse = "|") : object 'zipList' not found`
And on zipsByProduct() output, this error:
`Error in basename(zipList) : a character vector argument expected`

**Comment by NateMietk** [comment]
@cklunch there were a couple of typo's that were creating the problem.  Works now - please test

**Comment by cklunch** [comment]
Looking great, thanks!

**Pull request merged**
