### PR TITLE
Partly resolved Issue 75

### PR DESCRIPTION
**Pull request by NateMietk**
The main problem was download was hanging (https://github.com/NEONScience/NEON-utilities/issues/75), but that was not on the neonUtilities side of things.  A cache refresh solved the problem on its own, but added while loop checks, similar to https://github.com/NEONScience/NEON-utilities/issues/69, and this should solve any potential for future infinite while loops if a url is broken or there are no data found.

### CODE REVIEW

**Comment by cklunch** [comment]
@NateMietk 
It looks like this pull request contains the changes for both the byFileAOP() loop fix and the saveUnzippedFiles behavior. Can you remove the saveUnzippedFiles changes from this branch to keep things simple?

For the byFileAOP() changes, same comments as in byTileAOP(). Thanks!

**Comment by NateMietk** [comment]
@cklunch updated and push the original cleanUp function

**Comment by cklunch** [comment]
@NateMietk 
We shouldn't need the tileEasting and tileNorthing parameters here, since byFileAOP() doesn't allow subset by tile.

PR review now says there's a merge conflict on cleanUp.R, can you check it out?

**Comment by NateMietk** [comment]
@cklunch That's right - sorry about that.

**Comment by NateMietk** [comment]
@cklunch I believe this issue is now resolved. testUtilities comes up with no error and the files download without a problem.

**Comment by cklunch** [comment]
Looking good. Verified url regeneration is still happening, and updated doc files look fine.

**Pull request merged**
